// DNA: #龍芯⚡️丙午·丙申·壬戌·亥时·䷲震-AUDIT-TRACKER-v2.0-METHODOLOGY-WELD
// 创建者: 诸葛鑫（UID9622）
// 归属名: 诸葛鑫 | UID9622 · 龍芯北辰
// 协议: MulanPSL v2 (https://license.coscl.org.cn/MulanPSL2) — 工程实现层·允许商业使用
// 方法论来源: github.com/deepseek-ai/DeepSeek-V3/issues/1591 商讨共识
//   [DanceNitra] verdict 必须与 evidence 一致·未判定 ≠ 拒绝·三家族启发式
//   [icophy]    双层校准 Layer1 判定对齐 + Layer2 行为对齐
//   [baoqingkong66] 计数掩盖替换陷阱·报告必须附数据版本哈希
//   [UID9622]    审计探针可验证·报告示例双方示例·文档归宿统一
'use strict';

import * as vscode from 'vscode';
import * as crypto from 'crypto';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

// ─────────────────────────────────────────────
// 常量与元数据（P0·不可删）
// ─────────────────────────────────────────────
const BATCH_DNA = '#龍芯⚡️丙午·丙申·壬戌·亥时·䷲震-AUDIT-TRACKER-v2.0.1-UID9622';
const SEAL = '#ZHUGEXIN⚡️2025-🇨🇳🐉⚖️♠️🧚🏼‍♀️❤️♾️-DEVICE-BIND-SOUL';
const ATTRIBUTION = '诸葛鑫 | UID9622 · 龍芯北辰';
const VERSION = '2.0.1';

/** 三色审计标记（P05·GATE 三色体系） */
type ColorMark = '🟢' | '🟡' | '🔴';
/** AI 判定结论（对应 issue: FAIL 与 UNVERIFIABLE 必须分开） */
type Verdict = 'clean' | 'flagged' | 'unverified' | 'confirmed';
/** 人工复核状态 */
type ReviewStatus = 'pending' | 'reviewed' | 'rejected';
/** 启发式家族（对应 issue: 三家族启发式 = 关键词匹配/未明确判定/长度阈值） */
type EvidenceFamily = 'keyword' | 'pattern' | 'length';

interface Evidence {
  family: EvidenceFamily;
  label: string;
  detail: string;
}

interface AuditEntry {
  id: string;
  timestamp: string;
  modelSource: string;
  promptHash: string;
  codeHash: string;
  filePath: string;
  lineStart: number;
  lineEnd: number;
  codePreview: string;
  // v2.0 方法论字段
  verdict: Verdict;
  color: ColorMark;
  confidence: number;
  evidence: Evidence[];
  prevHash: string;         // 哈希链·防"计数掩盖替换"
  dna: string;              // 逐条独立 DNA（v∞）
  batchDna: string;
  behavior: { chars: number; lines: number; families: EvidenceFamily[] };
  reviewStatus: ReviewStatus;
  reviewTimestamp?: string;
  reviewer?: string;
  notes?: string;
}

interface AuditStats {
  total: number;
  pending: number;
  reviewed: number;
  rejected: number;
}

interface LogMeta {
  version: string;
  batchDna: string;
  seal: string;
  attribution: string;
  genesisHash: string;
  createdAt: string;
}

// ─────────────────────────────────────────────
// 启发式指纹库
// ─────────────────────────────────────────────
/** AI 注释/字符串标记（关键词匹配家族·H1） */
const AI_MARKERS: string[] = [
  'copilot', 'codeium', 'tabnine', 'ai-generated', 'ai generated',
  'generated by', 'generated with', 'generated using',
  'auto-generated', 'autogenerated', 'auto generated',
  'deepseek', 'chatgpt', 'claude', 'gemini', 'qwen', '通义', '文心',
  'kimi', 'moonshot', '豆包', 'doubao', '混元', 'hunyuan',
];

/** 中文 AI 写作特征模式（未明确判定家族·H2） */
const AI_PATTERNS: RegExp[] = [
  /下面是根据|以下是根据|根据你的要求|为你生成|希望对你有帮助|如果你需要.*可以/g,
  /\d+[、.]\s*(步骤|首先|然后|接着|最后|总结)/g,
  /(思考过程|推理步骤|分析如下|我们来分析|让我们从)/g,
  /(功能说明|使用说明|注意事项)[：:]?$/gm,
];

/** 模型指纹（含国内主流模型） */
const MODEL_FINGERPRINTS: Array<{ name: string; patterns: RegExp[] }> = [
  { name: 'DeepSeek', patterns: [/deepseek/i, /深度求索/i] },
  { name: 'CodeBuddy', patterns: [/codebuddy/i] },
  { name: 'Copilot', patterns: [/copilot/i, /github copilot/i] },
  { name: 'Codeium', patterns: [/codeium/i, /windsurf/i] },
  { name: 'ChatGPT', patterns: [/chatgpt/i, /openai/i, /gpt-?4/i, /gpt-?3/i] },
  { name: 'Claude', patterns: [/claude/i, /anthropic/i] },
  { name: 'Gemini', patterns: [/gemini/i, /bard/i] },
  { name: '通义千问', patterns: [/通义/i, /qwen/i] },
  { name: '文心一言', patterns: [/文心/i, /ernie/i] },
  { name: 'Kimi', patterns: [/kimi/i, /moonshot/i] },
  { name: '豆包', patterns: [/豆包/i, /doubao/i, /字节跳动|火山引擎/i] },
  { name: '混元', patterns: [/混元/i, /hunyuan/i, /腾讯云/i] },
];

// ─────────────────────────────────────────────
// 工具函数
// ─────────────────────────────────────────────
function sha256(input: string): string {
  return crypto.createHash('sha256').update(input).digest('hex');
}

function nowIso(): string {
  return new Date().toISOString().replace('T', ' ').substring(0, 19);
}

function shortId(hash: string): string {
  return hash.substring(0, 8);
}

/** 逐条独立 DNA（v∞ 标准：干支四柱或 YYYY-MM-DD） */
function perEntryDna(codeHash: string): string {
  const date = new Date().toISOString().substring(0, 10);
  return `#龍芯⚡️${date}-AUDIT-TRACKER-${shortId(codeHash)}`;
}

/** 哈希链：prev_hash 由上一条决定，防篡改 */
function chainHash(codeHash: string, verdict: Verdict, prevHash: string, ts: string, confidence: number, review: ReviewStatus): string {
  // v2.0.1 加固: 纳入 timestamp/confidence/reviewStatus，改时间·改置信度·改复核状态均会破链（P77 审计）
  return sha256(`${codeHash}|${verdict}|${confidence}|${review}|${ts}|${prevHash}`).substring(0, 16);
}

/** Wilson 95% 置信区间（issue: 小样本必须附 CI） */
function wilsonCI(n: number, k: number): { low: number; high: number } {
  if (n === 0) { return { low: 0, high: 0 }; }
  const z = 1.96;
  const p = k / n;
  const z2 = z * z;
  const center = (p + z2 / (2 * n)) / (1 + z2 / n);
  const half = (z * Math.sqrt(p * (1 - p) / n + z2 / (4 * n * n))) / (1 + z2 / n);
  return { low: Math.max(0, center - half), high: Math.min(1, center + half) };
}

/** 洛书数字根（369 体系·各位相加递归到一位·P06 数学大师·议事会 v2.0） */
function luoshuRoot(value: number | string): number {
  const digits = String(value).replace(/\D/g, '');
  if (!digits) { return 0; }
  let s = digits;
  while (s.length > 1) {
    let sum = 0;
    for (const ch of s) { sum += Number(ch); }
    s = String(sum);
  }
  return Number(s);
}

/** 模型来源检测 */
function detectModelSource(text: string): string {
  const lowered = text.toLowerCase();
  for (const fp of MODEL_FINGERPRINTS) {
    for (const re of fp.patterns) {
      if (re.test(lowered)) { return fp.name; }
    }
  }
  return '未知';
}

/** 启发式三家族检测（issue: 关键词匹配/未明确判定/长度阈值） */
function detectEvidence(text: string, minChars: number, minLines: number): Evidence[] {
  const evidence: Evidence[] = [];
  // H1 关键词匹配
  const kw = AI_MARKERS.filter((m) => text.toLowerCase().includes(m.toLowerCase()));
  if (kw.length > 0) {
    evidence.push({ family: 'keyword', label: '关键词匹配', detail: `命中: ${kw.slice(0, 5).join(', ')}` });
  }
  // H2 未明确判定（中文 AI 写作特征）
  const pats = AI_PATTERNS.filter((re) => re.test(text));
  if (pats.length > 0) {
    evidence.push({ family: 'pattern', label: '未明确判定', detail: `命中模式 ${pats.length} 类` });
  }
  // H3 长度阈值（大段粘贴行为）
  const lines = text.split('\n').length;
  if (text.length > minChars || lines > minLines) {
    evidence.push({ family: 'length', label: '长度阈值', detail: `${text.length}字符/${lines}行` });
  }
  return evidence;
}

/** verdict 判定（issue: verdict 必须与 evidence 一致·未判定≠拒绝） */
function classifyVerdict(evidence: Evidence[]): { verdict: Verdict; color: ColorMark; confidence: number } {
  if (evidence.length >= 2) { return { verdict: 'confirmed', color: '🔴', confidence: 0.9 }; }
  if (evidence.length === 1) { return { verdict: 'flagged', color: '🟡', confidence: 0.6 }; }
  // v2.0.1 修复(P04): 无任何启发式命中 = clean（🟢 落库统计）· unverified 仅保留给"有行为信号但无法确证"
  return { verdict: 'clean', color: '🟢', confidence: 0.85 };
}

function colorForStatus(s: ReviewStatus): ColorMark {
  if (s === 'rejected') { return '🔴'; }
  if (s === 'reviewed') { return '🟢'; }
  return '🟡';
}

// ─────────────────────────────────────────────
// 插件主体
// ─────────────────────────────────────────────
export function activate(context: vscode.ExtensionContext): void {
  const tracker = new AuditTracker(context);
  context.subscriptions.push(
    vscode.commands.registerCommand('longhun-audit.showAuditLog', () => tracker.showAuditView()),
    vscode.commands.registerCommand('longhun-audit.auditSelection', () => tracker.auditSelection()),
    vscode.commands.registerCommand('longhun-audit.markAsReviewed', () => tracker.markSelectionAsReviewed()),
    vscode.commands.registerCommand('longhun-audit.markAsRejected', () => tracker.markSelectionAsRejected()),
    vscode.commands.registerCommand('longhun-audit.generateReport', () => tracker.generateReport()),
    vscode.workspace.onDidChangeTextDocument((e) => tracker.onDocumentChange(e)),
    vscode.workspace.onDidSaveTextDocument((d) => tracker.onDocumentSave(d))
  );
  tracker.init();
}

export function deactivate(): void { /* 无持久资源 */ }

class AuditTracker {
  private logPath = '';
  private meta: LogMeta;
  private entries: AuditEntry[] = [];
  private panel: vscode.WebviewPanel | undefined;
  private filter: 'all' | ReviewStatus = 'all';
  /** v2.0.1(P01/P04): 双层校准闭环一致性断言失败计数 */
  private calibFailures = 0;

  constructor(private readonly context: vscode.ExtensionContext) {
    const cfg = vscode.workspace.getConfiguration('longhun-audit');
    const rel = cfg.get<string>('auditLogPath', '.audit/log.json');
    const root = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath ?? '';
    this.logPath = path.join(root, rel);
    this.meta = {
      version: VERSION,
      batchDna: BATCH_DNA,
      seal: SEAL,
      attribution: ATTRIBUTION,
      genesisHash: sha256(`${BATCH_DNA}|${SEAL}|${os.hostname()}`).substring(0, 16),
      createdAt: nowIso(),
    };
  }

  init(): void {
    this.ensureLogFile();
    this.loadLog();
  }

  // ── 日志读写 ──
  private ensureLogFile(): void {
    try {
      if (!this.logPath) { return; }
      const dir = path.dirname(this.logPath);
      if (!fs.existsSync(dir)) { fs.mkdirSync(dir, { recursive: true }); }
      if (!fs.existsSync(this.logPath)) {
        const seed: { meta: LogMeta; entries: AuditEntry[] } = { meta: this.meta, entries: [] };
        fs.writeFileSync(this.logPath, JSON.stringify(seed, null, 2), 'utf-8');
      }
    } catch { /* 静默 */ }
  }

  private loadLog(): void {
    try {
      const raw = fs.readFileSync(this.logPath, 'utf-8');
      const data = JSON.parse(raw);
      this.meta = { ...this.meta, ...data.meta };
      this.entries = data.entries ?? [];
    } catch {
      this.entries = [];
    }
  }

  private saveLog(): void {
    try {
      fs.writeFileSync(this.logPath, JSON.stringify({ meta: this.meta, entries: this.entries }, null, 2), 'utf-8');
    } catch { /* 静默 */ }
  }

  private stats(): AuditStats {
    const s: AuditStats = { total: this.entries.length, pending: 0, reviewed: 0, rejected: 0 };
    for (const e of this.entries) {
      if (e.reviewStatus === 'reviewed') { s.reviewed++; }
      else if (e.reviewStatus === 'rejected') { s.rejected++; }
      else { s.pending++; }
    }
    return s;
  }

  private lastHash(): string {
    const last = this.entries[this.entries.length - 1];
    return last ? last.prevHash : this.meta.genesisHash;
  }

  private writeAuditEntry(
    promptHash: string, codeHash: string, filePath: string,
    lineStart: number, lineEnd: number, codePreview: string,
    evidence: Evidence[], modelSource: string, behavior: { chars: number; lines: number; families: EvidenceFamily[] }
  ): void {
    if (this.entries.some((e) => e.codeHash === codeHash && e.lineStart === lineStart)) { return; }
    const { verdict, color, confidence } = classifyVerdict(evidence);
    const timestamp = nowIso();
    const prevHash = chainHash(codeHash, verdict, this.lastHash(), timestamp, confidence, 'pending');
    // Layer1/Layer2 双层校准闭环断言（icophy·issue#1591）：verdict 必须与 evidence 一致
    if ((verdict === 'clean' && evidence.length > 0) || (verdict !== 'clean' && evidence.length === 0)) {
      this.calibFailures++;
      console.warn('[audit-tracker] ⚠️ 一致性断言失败 verdict/evidence 不匹配:', verdict, evidence.length);
    }
    const entry: AuditEntry = {
      id: `${shortId(codeHash)}-${this.entries.length + 1}`,
      timestamp,
      modelSource,
      promptHash,
      codeHash,
      filePath,
      lineStart,
      lineEnd,
      codePreview: codePreview.substring(0, 300),
      verdict,
      color,
      confidence,
      evidence,
      prevHash,
      dna: perEntryDna(codeHash),
      batchDna: BATCH_DNA,
      behavior,
      reviewStatus: 'pending',
    };
    this.entries.push(entry);
    this.saveLog();
    this.refreshWebview();
  }

  // ── 事件监听（行为记录·Layer2） ──
  onDocumentChange(e: vscode.TextDocumentChangeEvent): void {
    const cfg = vscode.workspace.getConfiguration('longhun-audit');
    const minChars = cfg.get<number>('minPasteChars', 300);
    const minLines = cfg.get<number>('minPasteLines', 15);
    const c = e.contentChanges[e.contentChanges.length - 1];
    if (!c) { return; }
    const text = c.text;
    if (text.length < 50) { return; }
    const evidence = detectEvidence(text, minChars, minLines);
    // v2.0 方法论：任何启发式命中（含长度阈值=大段粘贴）都记录，verdict 分级而非跳过
    if (evidence.length === 0) { return; }
    const codeHash = sha256(text);
    const doc = e.document;
    const lineStart = doc.positionAt(doc.offsetAt(c.range.start)).line + 1;
    const lineEnd = doc.positionAt(doc.offsetAt(c.range.end)).line + 1;
    this.writeAuditEntry(
      shortId(codeHash),
      codeHash,
      path.basename(doc.uri.fsPath || '(untitled)'),
      lineStart, lineEnd, text,
      evidence,
      detectModelSource(text),
      { chars: text.length, lines: text.split('\n').length, families: evidence.map((ev) => ev.family) }
    );
  }

  onDocumentSave(doc: vscode.TextDocument): void {
    if (doc.languageId === 'json') { return; }
    const full = doc.getText();
    if (full.length < 100) { return; }
    const evidence = detectEvidence(full, Number.MAX_SAFE_INTEGER, 1000);
    const codeHash = sha256(full);
    // v2.0.1 修复(P04): clean 也落库（统计真实·clean 不再恒 0）· 按内容哈希去重防刷屏
    if (evidence.length === 0 && this.entries.some((e) => e.codeHash === codeHash && e.verdict === 'clean')) { return; }
    const markerLine = evidence.length === 0
      ? -1
      : full.split('\n').findIndex((line) =>
          AI_MARKERS.some((m) => line.toLowerCase().includes(m.toLowerCase()))
        );
    const lineStart = Math.max(1, markerLine + 1);
    const lineEnd = Math.min(full.split('\n').length, lineStart + 5);
    const block = evidence.length === 0
      ? full.split('\n').slice(0, lineEnd).join('\n')
      : full.split('\n').slice(markerLine, lineEnd).join('\n');
    this.writeAuditEntry(
      shortId(codeHash), codeHash,
      path.basename(doc.uri.fsPath),
      lineStart, lineEnd, block,
      evidence, detectModelSource(full),
      { chars: full.length, lines: full.split('\n').length, families: evidence.map((ev) => ev.family) }
    );
  }

  // ── 命令实现 ──
  auditSelection(): void {
    const ed = vscode.window.activeTextEditor;
    if (!ed) { vscode.window.showWarningMessage('没有活动编辑器'); return; }
    const sel = ed.selection;
    const text = ed.document.getText(sel);
    if (!text) { vscode.window.showWarningMessage('未选中任何代码'); return; }
    const cfg = vscode.workspace.getConfiguration('longhun-audit');
    const evidence = detectEvidence(text, cfg.get<number>('minPasteChars', 300), cfg.get<number>('minPasteLines', 15));
    const codeHash = sha256(text);
    if (this.entries.some((e) => e.codeHash === codeHash)) {
      vscode.window.showInformationMessage('该代码段已在审计日志中');
      return;
    }
    const { verdict, color, confidence } = classifyVerdict(evidence);
    const timestamp = nowIso();
    const prevHash = chainHash(codeHash, verdict, this.lastHash(), timestamp, confidence, 'pending');
    const entry: AuditEntry = {
      id: `${shortId(codeHash)}-${this.entries.length + 1}`,
      timestamp,
      modelSource: detectModelSource(text),
      promptHash: shortId(codeHash),
      codeHash,
      filePath: path.basename(ed.document.uri.fsPath),
      lineStart: sel.start.line + 1,
      lineEnd: sel.end.line + 1,
      codePreview: text.substring(0, 300),
      verdict, color, confidence,
      evidence, prevHash,
      dna: perEntryDna(codeHash), batchDna: BATCH_DNA,
      behavior: { chars: text.length, lines: text.split('\n').length, families: evidence.map((ev) => ev.family) },
      reviewStatus: 'pending',
    };
    this.entries.push(entry);
    this.saveLog();
    this.refreshWebview();
    vscode.window.showInformationMessage(`已记录审计: ${verdict} ${color}`);
  }

  markSelectionAsReviewed(): void {
    const ed = vscode.window.activeTextEditor;
    if (!ed) { vscode.window.showWarningMessage('没有活动编辑器'); return; }
    const text = ed.document.getText(ed.selection);
    if (!text) { vscode.window.showWarningMessage('未选中任何代码'); return; }
    const codeHash = sha256(text);
    const hit = this.entries.find((e) => e.codeHash === codeHash);
    if (!hit) { vscode.window.showWarningMessage('该代码段不在审计日志中'); return; }
    hit.reviewStatus = 'reviewed';
    hit.reviewTimestamp = nowIso();
    hit.reviewer = ATTRIBUTION;
    this.saveLog();
    this.refreshWebview();
    vscode.window.showInformationMessage('已标记为已审核（🟢）');
  }

  markSelectionAsRejected(): void {
    const ed = vscode.window.activeTextEditor;
    if (!ed) { vscode.window.showWarningMessage('没有活动编辑器'); return; }
    const sel = ed.selection;
    const text = ed.document.getText(sel);
    if (!text) { vscode.window.showWarningMessage('未选中任何代码'); return; }
    const codeHash = sha256(text);
    const hit = this.entries.find((e) => e.codeHash === codeHash);
    if (hit) {
      hit.reviewStatus = 'rejected';
      hit.reviewTimestamp = nowIso();
      hit.reviewer = ATTRIBUTION;
      this.saveLog();
      this.refreshWebview();
      vscode.window.showInformationMessage('已标记为拒绝（🔴）');
    } else {
      // 未记录过则立即记录并标记
      const evidence = detectEvidence(text, 300, 15);
      const timestamp = nowIso();
      const prevHash = chainHash(codeHash, 'confirmed', this.lastHash(), timestamp, 1, 'rejected');
      const entry: AuditEntry = {
        id: `${shortId(codeHash)}-${this.entries.length + 1}`,
        timestamp,
        modelSource: detectModelSource(text),
        promptHash: shortId(codeHash),
        codeHash,
        filePath: path.basename(ed.document.uri.fsPath),
        lineStart: sel.start.line + 1,
        lineEnd: sel.end.line + 1,
        codePreview: text.substring(0, 300),
        verdict: 'confirmed', color: '🔴', confidence: 1,
        evidence, prevHash,
        dna: perEntryDna(codeHash), batchDna: BATCH_DNA,
        behavior: { chars: text.length, lines: text.split('\n').length, families: evidence.map((ev) => ev.family) },
        reviewStatus: 'rejected',
        reviewTimestamp: nowIso(),
        reviewer: ATTRIBUTION,
      };
      this.entries.push(entry);
      this.saveLog();
      this.refreshWebview();
      vscode.window.showInformationMessage('已记录并标记为拒绝（🔴）');
    }
  }

  generateReport(): void {
    const report = this.buildReport();
    vscode.window.showTextDocument(
      vscode.Uri.file(path.join(path.dirname(this.logPath), 'audit-report.md')),
      { preview: true }
    ).then(() => {}, () => {});
    fs.writeFileSync(path.join(path.dirname(this.logPath), 'audit-report.md'), report, 'utf-8');
    vscode.window.showInformationMessage('审计报告已生成');
  }

  // ── 报告（含 Wilson CI + 哈希链校验 + 三家族分布） ──
  private buildReport(): string {
    const s = this.stats();
    const rejected = this.entries.filter((e) => e.reviewStatus === 'rejected').length;
    const ci = wilsonCI(s.total, rejected);
    // 哈希链校验
    let chainOk = true;
    let prev = this.meta.genesisHash;
    for (const e of this.entries) {
      if (e.prevHash !== prev) { chainOk = false; break; }
      prev = chainHash(e.codeHash, e.verdict, e.prevHash, e.timestamp, e.confidence, e.reviewStatus);
    }
    // 三家族分布
    const famCount: Record<string, number> = { keyword: 0, pattern: 0, length: 0 };
    for (const e of this.entries) {
      for (const ev of e.evidence) { famCount[ev.family] = (famCount[ev.family] ?? 0) + 1; }
    }
    const verdictCount: Record<string, number> = { clean: 0, flagged: 0, unverified: 0, confirmed: 0 };
    for (const e of this.entries) { verdictCount[e.verdict] = (verdictCount[e.verdict] ?? 0) + 1; }

    // v2.0.1(P06/P01/P04·议事会 v2.0): 数字根双闸 + 双层校准二期指标 + 模型指纹分布
    const rootTotal = luoshuRoot(s.total);
    const dnaRoot = luoshuRoot(BATCH_DNA.slice(-8));
    const rootPhase = rootTotal === 3 || rootTotal === 6 || rootTotal === 9 ? `相位命中(${rootTotal})` : `相位(${rootTotal})`;
    const rootGate = rootTotal === dnaRoot ? '✅ 一致' : '🟡 偏差(需人工复核)';
    const calibOk = Math.max(0, s.total - this.calibFailures);
    const calibRate = s.total > 0 ? ((calibOk / s.total) * 100).toFixed(1) + '%' : '—';
    const modelCount: Record<string, number> = {};
    for (const e of this.entries) { modelCount[e.modelSource] = (modelCount[e.modelSource] ?? 0) + 1; }
    const modelRows = Object.entries(modelCount).map(([m, c]) => `- ${m}: ${c}`).join('\n') || '- 无记录';

    const rows = this.entries.map((e) =>
      `| ${e.id} | ${e.timestamp} | ${e.color} ${e.verdict} | ${e.modelSource} | ${e.filePath}:${e.lineStart}-${e.lineEnd} | ${e.evidence.map((ev) => ev.label).join('/') || '—'} | ${e.reviewStatus} |`
    ).join('\n');

    return [
      '# 龍魂 AI 代码审计报告',
      '',
      '> DNA: #龍芯⚡️丙午·丙申·壬戌·亥时·䷲震-AUDIT-TRACKER-v2.0-UID9622',
      '> 归属名: 诸葛鑫 | UID9622 · 龍芯北辰',
      `> 版本: v${VERSION} · 生成时间: ${nowIso()} · 批DNA: ${BATCH_DNA}`,
      '',
      '## 统计总览',
      '',
      `| 指标 | 值 | 95% Wilson CI |`,
      `|---|---|---|`,
      `| 总记录 | ${s.total} | — |`,
      `| 待审核 🟡 | ${s.pending} | — |`,
      `| 已通过 🟢 | ${s.reviewed} | — |`,
      `| 已拒绝 🔴 | ${s.rejected} | ${ci.low.toFixed(3)}~${ci.high.toFixed(3)} |`,
      `| 哈希链完整 | ${chainOk ? '✅' : '🔴 篡改! '} | — |`,
      '',
      '## 判定分布（Layer1）',
      '',
      `- confirmed 🔴: ${verdictCount.confirmed}`,
      `- flagged 🟡: ${verdictCount.flagged}`,
      `- unverified 🟡（≠拒绝·待人工）: ${verdictCount.unverified}`,
      `- clean 🟢: ${verdictCount.clean}`,
      '',
      '## 数字根双闸（P06 · 洛书369）',
      '',
      '| 闸 | 计算 | 结果 |',
      '|---|---|---|',
      `| 闸1 计数闸 | total=${s.total} → 数字根 ${rootTotal} | ${rootPhase} |`,
      `| 闸2 哈希闸 | BATCH_DNA 末8位 → 数字根 ${dnaRoot} | ${rootGate} |`,
      '',
      '> 依据: 洛书九宫不动点 369 · 三才算法 · 双闸一致才放行，偏差需人工复核。',
      '',
      '## 双层校准闭环二期（P01/P04 · Layer1×Layer2）',
      '',
      `- 一致性断言: ${s.total} 次 · 失败 ${this.calibFailures} 次 · 一致性率 ${calibRate}`,
      '- 含义: verdict 必须与 evidence 一致（icophy 双层校准）· unverified ≠ rejected',
      '',
      '## 模型来源指纹分布（Layer2）',
      '',
      modelRows,
      '',
      '## 启发式家族分布（Layer2 行为）',
      '',
      `- 关键词匹配: ${famCount.keyword}`,
      `- 未明确判定: ${famCount.pattern}`,
      `- 长度阈值: ${famCount.length}`,
      '',
      '> 方法论注: verdict 必须与 evidence 一致；unverified 不等于 rejected；',
      '> 计数不变不等于内容不变（防"计数掩盖替换"·以哈希链为准）。',
      '',
      '## 逐条明细',
      '',
      '| ID | 时间 | 判定 | 模型 | 位置 | 启发式 | 复核 |',
      '|---|---|---|---|---|---|---|',
      rows || '| — | 无记录 | — | — | — | — | — |',
      '',
      `> 审计探针: 可复现命令 \`npm run compile\` + 日志文件 ${path.basename(this.logPath)} 可独立校验。`,
      '',
    ].join('\n');
  }

  // ── WebView ──
  showAuditView(): void {
    if (this.panel) {
      this.panel.reveal(vscode.ViewColumn.Beside);
      this.refreshWebview();
      return;
    }
    this.panel = vscode.window.createWebviewPanel(
      'longhunAudit', '龍魂 AI 代码审计日志', vscode.ViewColumn.Beside,
      { enableScripts: true, retainContextWhenHidden: true }
    );
    this.panel.onDidDispose(() => { this.panel = undefined; }, null, this.context.subscriptions);
    this.panel.webview.onDidReceiveMessage((msg) => this.handleWebviewMessage(msg), null, this.context.subscriptions);
    this.refreshWebview();
  }

  private refreshWebview(): void {
    if (!this.panel) { return; }
    this.panel.webview.html = this.buildHtml();
  }

  private handleWebviewMessage(msg: { type: string; id?: string; reason?: string }): void {
    if (!msg || typeof msg.type !== 'string') { return; }
    if (msg.type === 'markReviewed' && msg.id) {
      const e = this.entries.find((x) => x.id === msg.id);
      if (e) {
        e.reviewStatus = 'reviewed'; e.reviewTimestamp = nowIso(); e.reviewer = ATTRIBUTION;
        this.saveLog(); this.refreshWebview();
      }
    } else if (msg.type === 'markRejected' && msg.id) {
      const e = this.entries.find((x) => x.id === msg.id);
      if (e) {
        e.reviewStatus = 'rejected'; e.reviewTimestamp = nowIso(); e.reviewer = ATTRIBUTION;
        e.notes = msg.reason || undefined;
        this.saveLog(); this.refreshWebview();
      }
    } else if (msg.type === 'filter') {
      this.filter = (msg as { type: string; filter?: 'all' | ReviewStatus }).filter ?? 'all';
      this.refreshWebview();
    }
  }

  private buildHtml(): string {
    const s = this.stats();
    const filtered = this.filter === 'all' ? this.entries : this.entries.filter((e) => e.reviewStatus === this.filter);
    const rows = filtered.map((e) => {
      const fams = e.evidence.map((ev) => `<span class="tag">${ev.label}</span>`).join('');
      return `<div class="row" onclick="toggleDetail('${e.id}')">
        <span class="mark">${e.color}</span>
        <span class="id">${e.id}</span>
        <span class="t">${e.timestamp.substring(5, 16)}</span>
        <span class="m">${e.modelSource}</span>
        <span class="v v-${e.verdict}">${e.verdict}(${Math.round(e.confidence * 100)}%)</span>
        <span class="f">${e.filePath}:${e.lineStart}-${e.lineEnd}</span>
        <span class="acts">
          <button onclick="mark(event,'${e.id}','reviewed')">✅</button>
          <button onclick="mark(event,'${e.id}','rejected')">🔴</button>
        </span>
        <div class="detail" id="d-${e.id}" style="display:none">
          <div>DNA: ${e.dna}</div>
          <div>代码哈希: ${shortId(e.codeHash)} · 上链: ${e.prevHash}</div>
          ${e.evidence.map((ev) => `<div class="ev">【${ev.label}】${ev.detail}</div>`).join('') || '<div class="ev">无启发式命中·记录于人工判定</div>'}
          <pre>${escapeHtml(e.codePreview)}</pre>
          ${e.notes ? `<div>备注: ${escapeHtml(e.notes)}</div>` : ''}
        </div>
      </div>`;
    }).join('');

    return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<style>
  body { font-family: -apple-system, "PingFang SC", sans-serif; padding: 8px; color: #d0d0d0; background: #1e1e2e; }
  h1 { font-size: 15px; margin: 4px 0 8px; }
  .stats { display: flex; gap: 8px; margin-bottom: 8px; font-size: 12px; }
  .chip { background: #2a2a3e; padding: 3px 8px; border-radius: 10px; }
  .chip b { color: #fff; }
  .filters { margin-bottom: 8px; }
  .filters button { background: #3a3a52; border: 0; color: #ccc; padding: 3px 10px; margin-right: 4px; border-radius: 8px; cursor: pointer; }
  .filters button.on { background: #5a5a7a; color: #fff; }
  .row { background: #252537; border-radius: 8px; padding: 6px 8px; margin-bottom: 6px; cursor: pointer; display: flex; flex-wrap: wrap; align-items: center; gap: 8px; font-size: 12px; }
  .mark { font-size: 14px; }
  .id { color: #7dd3fc; font-family: monospace; }
  .t { color: #888; }
  .m { color: #f9a8d4; }
  .v { padding: 1px 6px; border-radius: 8px; font-family: monospace; }
  .v-confirmed { background: #7f1d1d; color: #fca5a5; }
  .v-flagged { background: #713f12; color: #fde68a; }
  .v-unverified { background: #713f12; color: #fde68a; }
  .v-clean { background: #14532d; color: #86efac; }
  .f { color: #93c5fd; }
  .acts button { border: 0; background: transparent; cursor: pointer; font-size: 13px; }
  .detail { flex-basis: 100%; border-top: 1px solid #333; margin-top: 4px; padding-top: 4px; color: #aaa; font-size: 11px; word-break: break-all; }
  .ev { margin: 2px 0; }
  .tag { background: #3f3f5e; color: #c4b5fd; border-radius: 6px; padding: 0 5px; font-size: 10px; }
  pre { background: #1a1a2a; padding: 6px; border-radius: 6px; overflow-x: auto; max-height: 160px; color: #b8b8c8; white-space: pre-wrap; }
</style>
</head>
<body>
<h1>龍魂 AI 代码审计日志 <small style="color:#777">v${VERSION}</small></h1>
<div class="stats">
  <span class="chip">总记录 <b>${s.total}</b></span>
  <span class="chip">待审核 <b>${s.pending}</b></span>
  <span class="chip">已通过 <b>${s.reviewed}</b></span>
  <span class="chip">已拒绝 <b>${s.rejected}</b></span>
</div>
<div class="filters">
  ${(['all', 'pending', 'reviewed', 'rejected'] as const).map((f) =>
    `<button class="${this.filter === f ? 'on' : ''}" onclick="setFilter('${f}')">${f === 'all' ? '全部' : f === 'pending' ? '待审核' : f === 'reviewed' ? '已通过' : '已拒绝'}</button>`
  ).join('')}
</div>
<div id="list">${rows || '<div style="color:#666;padding:12px">暂无记录</div>'}</div>
<script>
  const vscode = acquireVsCodeApi();
  function toggleDetail(id) { const d = document.getElementById('d-' + id); d.style.display = d.style.display === 'none' ? 'block' : 'none'; }
  function setFilter(f) { vscode.postMessage({ type: 'filter', filter: f }); }
  function mark(ev, id, st) { ev.stopPropagation(); vscode.postMessage({ type: st === 'reviewed' ? 'markReviewed' : 'markRejected', id: id }); }
</script>
</body>
</html>`;
  }
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
