// Generated by CNSH Compiler v1.0 (Python)
// DNA追溯码：#龍芯⚡️2026-02-02-CNSH编译输出
// GPG指纹：A2D0092CEE2E5BA87035600924C3704A8CC26D5F

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

/* ═══════════════════════════════════════════════════
   CNSH 标准库 v1.0
   DNA: #龍芯⚡️2026-03-22-CNSH-STDLIB-v1.0
   UID: UID9622 | 创建者: 诸葛鑫
   ═══════════════════════════════════════════════════ */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>
#include <time.h>

/* ── 内存安全：字符串缓冲区 ── */
#define CNSH_BUF_SIZE 4096
static char __cnsh_str_buf[64][CNSH_BUF_SIZE];
static int  __cnsh_buf_idx = 0;

static char* __cnsh_next_buf() {
    __cnsh_buf_idx = (__cnsh_buf_idx + 1) % 64;
    __cnsh_str_buf[__cnsh_buf_idx][0] = '\0';
    return __cnsh_str_buf[__cnsh_buf_idx];
}

/* ── io 模块 ── */

/* 打印整数 */
void 打印整数(int n) {
    printf("%d\n", n);
}

/* 打印小数 */
void 打印小数(double d) {
    printf("%g\n", d);
}

/* 打印文本 */
void 打印文本(const char* s) {
    if (s) printf("%s\n", s);
    else   printf("\n");
}

/* 打印布尔 */
void 打印真假(bool b) {
    printf("%s\n", b ? "真" : "假");
}

/* ── string 模块 ── */

/* 拼接两个字符串 */
char* 拼接(const char* a, const char* b) {
    char* buf = __cnsh_next_buf();
    if (a) strncpy(buf, a, CNSH_BUF_SIZE - 1);
    if (b) strncat(buf, b, CNSH_BUF_SIZE - 1 - strlen(buf));
    return buf;
}

/* 整数转文本 */
char* 转文本(int n) {
    char* buf = __cnsh_next_buf();
    snprintf(buf, CNSH_BUF_SIZE, "%d", n);
    return buf;
}

/* 小数转文本 */
char* 小数转文本(double d) {
    char* buf = __cnsh_next_buf();
    snprintf(buf, CNSH_BUF_SIZE, "%g", d);
    return buf;
}

/* 取字符串长度 */
int 取长度(const char* s) {
    if (!s) return 0;
    return (int)strlen(s);
}

/* 截取字符串：从 start 开始取 len 个字节 */
char* 截取(const char* s, int start, int len) {
    char* buf = __cnsh_next_buf();
    if (!s || start < 0 || len <= 0) return buf;
    int slen = (int)strlen(s);
    if (start >= slen) return buf;
    int actual = (start + len > slen) ? slen - start : len;
    strncpy(buf, s + start, actual);
    buf[actual] = '\0';
    return buf;
}

/* ── math 模块 ── */

/* 绝对值 */
int 绝对值(int n) { return abs(n); }

/* 最大值 */
int 最大值(int a, int b) { return a > b ? a : b; }

/* 最小值 */
int 最小值(int a, int b) { return a < b ? a : b; }

/* 幂运算（整数） */
int 幂(int base, int exp) {
    int result = 1;
    for (int i = 0; i < exp; i++) result *= base;
    return result;
}

/* ── time 模块 ── */

/* 获取当前时间戳（秒） */
long 时间戳() {
    return (long)time(NULL);
}

/* ── system 模块 ── */

/* 退出程序 */
void 退出(int code) {
    exit(code);
}

/* ═══════════════════════════════════════════════════
   CNSH 标准库注入完成
   ═══════════════════════════════════════════════════ */


int 主函数() {
    printf("%s\n", "━━━━━━━━━━━━━━━━━━");
    printf("%s\n", "🇨🇳 你好，CNSH语言！");
    printf("%s\n", "━━━━━━━━━━━━━━━━━━");
    printf("%s\n", "");
    int 成本 = 80;
    int 售价 = 120;
    int 利润 = (售价 - 成本);
    printf("%s\n", "成本：80");
    printf("%s\n", "售价：120");
    printf("%s\n", "利润：40");
    printf("%s\n", "");
    if ((利润 > 0)) {
        printf("%s\n", "✅ 有利润");
    } else {
        printf("%s\n", "❌ 亏损");
    }
    printf("%s\n", "");
    printf("%s\n", "━━━━━━━━━━━━━━━━━━");
    printf("%s\n", "循环测试：");
    for (int __i = 0; __i < 3; __i++) {
        printf("%s\n", "  🔄 测试循环执行...");
    }
    printf("%s\n", "━━━━━━━━━━━━━━━━━━");
    printf("%s\n", "");
    printf("%s\n", "✅ CNSH程序执行完成！");
    printf("%s\n", "🧬 DNA追溯已生效");
    printf("%s\n", "🇨🇳 中国原生编程语言");
    return 0;
}


int main() {
    主函数();
    return 0;
}