#龍芯⚡️丙午·丙申·己未·乙亥时·䷞旅-LIMITS-TUNE-v1.0-UID9622
# CONFIRM: #CONFIRM🌌9622-ONLY-ONCE🧬LK9X-772Z
# GPG: A2D0092CEE2E5BA87035600924C3704A8CC26D5F
# SPDX-License-Identifier: MulanPSL-2.0
# /etc/security/limits.d/99-longhun.conf —— 龍魂 · 系统资源限制

* soft nofile 65535
* hard nofile 65535
* soft nproc 65535
* hard nproc 65535
www-data soft nofile 65535
www-data hard nofile 65535
