# -*- coding: utf-8 -*-
"""
CNSH v2.1 Token 定义
DNA: #龍芯⚡️2026-06-29-CNSH-TOKENS-v2.1
"""
from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class Token:
    type: str
    value: str
    line: int
    column: int
    file: Optional[str] = None

    def __repr__(self) -> str:
        return f"Token({self.type}, {self.value!r}, L{self.line}, C{self.column})"


# Token 类型常量
TOKEN_TYPES = {
    # 字面量
    "NUMBER": "NUMBER",
    "STRING": "STRING",
    "BOOLEAN": "BOOLEAN",
    "NULL": "NULL",
    # 关键字
    "KEYWORD": "KEYWORD",
    # 标识符
    "IDENTIFIER": "IDENTIFIER",
    # 算术运算符
    "PLUS": "PLUS",
    "MINUS": "MINUS",
    "STAR": "STAR",
    "SLASH": "SLASH",
    "PERCENT": "PERCENT",
    "POWER": "POWER",
    "FLOOR_DIV": "FLOOR_DIV",
    # 赋值运算符
    "ASSIGN": "ASSIGN",
    "PLUS_ASSIGN": "PLUS_ASSIGN",
    "MINUS_ASSIGN": "MINUS_ASSIGN",
    "STAR_ASSIGN": "STAR_ASSIGN",
    "SLASH_ASSIGN": "SLASH_ASSIGN",
    "PERCENT_ASSIGN": "PERCENT_ASSIGN",
    # 比较运算符
    "EQ": "EQ",
    "NE": "NE",
    "LT": "LT",
    "GT": "GT",
    "LE": "LE",
    "GE": "GE",
    # 逻辑运算符
    "AND": "AND",
    "OR": "OR",
    "NOT": "NOT",
    # 成员运算符
    "CONTAINS": "CONTAINS",
    "EXISTS": "EXISTS",
    "BELONGS_TO": "BELONGS_TO",
    # 标点
    "LPAREN": "LPAREN",
    "RPAREN": "RPAREN",
    "LBRACE": "LBRACE",
    "RBRACE": "RBRACE",
    "LBRACKET": "LBRACKET",
    "RBRACKET": "RBRACKET",
    "COMMA": "COMMA",
    "SEMICOLON": "SEMICOLON",
    "COLON": "COLON",
    "DOT": "DOT",
    "WEIGHT": "WEIGHT",
    "ARROW": "ARROW",
    "AT": "AT",
    "NEWLINE": "NEWLINE",
    "EOF": "EOF",
    "COMMENT": "COMMENT",
    "DNA_COMMENT": "DNA_COMMENT",
    # 分支选择
    "SWITCH": "SWITCH",
    "CASE": "CASE",
    "DEFAULT": "DEFAULT",
    # 数据类型关键字
    "STRING_TYPE": "STRING_TYPE",
    "INTEGER_TYPE": "INTEGER_TYPE",
    "FLOAT_TYPE": "FLOAT_TYPE",
    "BOOLEAN_TYPE": "BOOLEAN_TYPE",
    "LIST_TYPE": "LIST_TYPE",
    "ARRAY_TYPE": "ARRAY_TYPE",
    "MAP_TYPE": "MAP_TYPE",
    "VECTOR_TYPE": "VECTOR_TYPE",
    "BINARY_TYPE": "BINARY_TYPE",
    # 声明关键字
    "ENTRY": "ENTRY",
    "GLOBAL": "GLOBAL",
    "LOCAL": "LOCAL",
    "CONFIG": "CONFIG",
    "CACHE": "CACHE",
    # 操作关键字
    "CALL": "CALL",
    "NEW": "NEW",
    "APPEND": "APPEND",
    "INSERT": "INSERT",
    "DELETE_KW": "DELETE_KW",
    "REPLACE": "REPLACE",
    "READ": "READ",
    "WRITE": "WRITE",
    "PRINT": "PRINT",
    "EXPORT": "EXPORT",
    "COPY": "COPY",
    "MOVE": "MOVE",
    "IN": "IN",
    # OOP 关键字
    "CLASS": "CLASS",
    "DEF": "DEF",
    "SELF": "SELF",
    "SUPER": "SUPER",
    "YIELD": "YIELD",
    "YIELD_FROM": "YIELD_FROM",
    "ASYNC": "ASYNC",
    "AWAIT": "AWAIT",
    "WITH": "WITH",
    "AS": "AS",
    "TRY": "TRY",
    "EXCEPT": "EXCEPT",
    "FINALLY": "FINALLY",
    "RAISE": "RAISE",
    "PASS": "PASS",
    "IMPORT": "IMPORT",
    "FROM": "FROM",
    "ENUM": "ENUM",
    "UNIQUE": "UNIQUE",
    "DATACLASS": "DATACLASS",
    "FIELD": "FIELD",
    "DEFAULT_FACTORY": "DEFAULT_FACTORY",
    "PROPERTY": "PROPERTY",
    "CLASSMETHOD": "CLASSMETHOD",
    "STATICMETHOD": "STATICMETHOD",
    "ABSTRACTMETHOD": "ABSTRACTMETHOD",
    "OBJECT": "OBJECT",
    "INSTANCE": "INSTANCE",
    "EXTENDS": "EXTENDS",
    "INTERFACE": "INTERFACE",
    "ABSTRACT": "ABSTRACT",
    "VIRTUAL": "VIRTUAL",
    "GENERIC": "GENERIC",
    "OVERLOAD": "OVERLOAD",
    "OVERRIDE": "OVERRIDE",
    "CONSTRUCTOR": "CONSTRUCTOR",
    "DESTRUCTOR": "DESTRUCTOR",
    "PUBLIC": "PUBLIC",
    "PRIVATE": "PRIVATE",
    "PROTECTED": "PROTECTED",
    "INTERNAL": "INTERNAL",
    "ITERATOR": "ITERATOR",
    "GENERATOR": "GENERATOR",
    "STREAM": "STREAM",
    "COROUTINE": "COROUTINE",
    "THREAD": "THREAD",
    "MUTEX": "MUTEX",
    "ATOMIC": "ATOMIC",
    "CHANNEL": "CHANNEL",
    "SEMAPHORE": "SEMAPHORE",
    "PARALLEL": "PARALLEL",
    "SERIAL": "SERIAL",
    "ERROR_OBJECT": "ERROR_OBJECT",
    "TEST": "TEST",
    "ASSERT": "ASSERT",
    "EXPECT": "EXPECT",
    "RANGE": "RANGE",
    # Bra-Ket 人格协作关键字
    "PERSONA_BASIS": "PERSONA_BASIS",
    "SYSTEM": "SYSTEM",
    # 龍魂专属关键字
    "TRI_COLOR_AUDIT": "TRI_COLOR_AUDIT",
    "AUDITING": "AUDITING",
    "AUDITED": "AUDITED",
    "DNA_TRACE": "DNA_TRACE",
    "DNA_REGISTER": "DNA_REGISTER",
    "DNA_VERIFY": "DNA_VERIFY",
    "DNA_SIGN": "DNA_SIGN",
    "QUANTUM_ENTANGLE": "QUANTUM_ENTANGLE",
    "QUANTUM_STATE": "QUANTUM_STATE",
    "SUPERPOSITION": "SUPERPOSITION",
    "COLLAPSE": "COLLAPSE",
    "CREATE_ROLLBACK": "CREATE_ROLLBACK",
    "ROLLBACK": "ROLLBACK",
    "VERIFY_ROLLBACK": "VERIFY_ROLLBACK",
    "HOOK": "HOOK",
    "BEFORE_HOOK": "BEFORE_HOOK",
    "AFTER_HOOK": "AFTER_HOOK",
    "ABORT": "ABORT",
    "COLD_START": "COLD_START",
    "HOT_START": "HOT_START",
    "EXIT_PROGRAM": "EXIT_PROGRAM",
    "ROUTE": "ROUTE",
    "INTENT": "INTENT",
    "CONTEXT": "CONTEXT",
    "ROUTE_TO": "ROUTE_TO",
    "HIT": "HIT",
    "DISPATCH": "DISPATCH",
    "SUBSCRIBE": "SUBSCRIBE",
    "PUBLISH": "PUBLISH",
    "ENCRYPT_KW": "ENCRYPT_KW",
    "DECRYPT_KW": "DECRYPT_KW",
    "SIGN_MSG": "SIGN_MSG",
    "VERIFY_SIGN": "VERIFY_SIGN",
    "DIGITAL_ROOT": "DIGITAL_ROOT",
    "DR_FUSE": "DR_FUSE",
    "WUXING": "WUXING",
    "BAGUA": "BAGUA",
    "TIANGAN": "TIANGAN",
    "DIZHI": "DIZHI",
    "SANCAI": "SANCAI",
    "TAIJI": "TAIJI",
    "MENGGUA": "MENGGUA",
    "ENLIGHTEN": "ENLIGHTEN",
    "LONGDUN": "LONGDUN",
    "ETE": "ETE",
    "WARNING_PRE": "WARNING_PRE",
    "ALERT": "ALERT",
    "BLACKLIST": "BLACKLIST",
    "RED_LINE_WORD": "RED_LINE_WORD",
    "RED_LINE_SET": "RED_LINE_SET",
    "NOW_FN": "NOW_FN",
    "LEN_FN": "LEN_FN",
    "TO_STR_FN": "TO_STR_FN",
    "TO_INT_FN": "TO_INT_FN",
}


# 关键字映射
KEYWORDS = {
    # ── 控制流 ──
    "模块": "MODULE",
    "函数": "FUNCTION",
    "定义": "DEF",
    "类": "CLASS",
    "自己": "SELF",
    "超类": "SUPER",
    "变量": "VAR",
    "常量": "CONST",
    "结构体": "STRUCT",
    "返回": "RETURN",
    "如果": "IF",
    "否则如果": "ELIF",
    "否则": "ELSE",
    "循环": "LOOP",
    "当": "WHILE",
    "对于": "FOR",
    "在": "IN",
    "异步": "ASYNC",
    "等待": "AWAIT",
    "中断": "BREAK",
    "跳出": "BREAK",
    "继续": "CONTINUE",
    "使用": "WITH",
    "作为": "AS",
    "导入": "IMPORT",
    "导出": "EXPORT",
    "从": "FROM",
    "尝试": "TRY",
    "捕获": "EXCEPT",
    "最终": "FINALLY",
    "抛出": "RAISE",
    "通过": "PASS",
    "产生": "YIELD",
    "产生于": "YIELD_FROM",
    "真": "TRUE",
    "假": "FALSE",
    "空": "NULL",
    # ── 分支选择（v2.0 新增） ──
    "切换": "SWITCH",
    "情况": "CASE",
    "默认": "DEFAULT",
    # ── 数据类型 ──
    "字符串": "STRING_TYPE",
    "整数": "INTEGER_TYPE",
    "浮点数": "FLOAT_TYPE",
    "布尔": "BOOLEAN_TYPE",
    "列表": "LIST_TYPE",
    "数组": "ARRAY_TYPE",
    "映射": "MAP_TYPE",
    "向量": "VECTOR_TYPE",
    "二进制": "BINARY_TYPE",
    # ── 声明关键字 ──
    "入口": "ENTRY",
    "全局": "GLOBAL",
    "局部": "LOCAL",
    "配置": "CONFIG",
    "缓存": "CACHE",
    # ── 操作关键字 ──
    "调用": "CALL",
    "新建": "NEW",
    "添加": "APPEND",
    "插入": "INSERT",
    "删除": "DELETE",
    "替换": "REPLACE",
    "读取": "READ",
    "写入": "WRITE",
    "输出": "PRINT",
    "复制": "COPY",
    "移动": "MOVE",
    # ── 逻辑运算符别名 ──
    "且": "AND",
    "或": "OR",
    "非": "NOT",
    "等于": "EQ",
    "不等于": "NE",
    "大于": "GT",
    "小于": "LT",
    "大于等于": "GE",
    "小于等于": "LE",
    "包含": "CONTAINS",
    "存在": "EXISTS",
    "属于": "BELONGS_TO",
    # ── 赋值运算符 ──
    "加赋": "PLUS_ASSIGN",
    "减赋": "MINUS_ASSIGN",
    "乘赋": "STAR_ASSIGN",
    "除赋": "SLASH_ASSIGN",
    "余赋": "PERCENT_ASSIGN",
    # ── 错误处理关键字 ──
    "错误对象": "ERROR_OBJECT",
    # ── 测试关键字 ──
    "测试": "TEST",
    "断言": "ASSERT",
    "期望": "EXPECT",
    "范围": "RANGE",
    # ── 龍魂专属装饰器/类型关键字 ──
    "枚举类": "ENUM",
    "枚举唯一": "UNIQUE",
    "数据类": "DATACLASS",
    "字段": "FIELD",
    "默认工厂": "DEFAULT_FACTORY",
    "属性": "PROPERTY",
    "类方法": "CLASSMETHOD",
    "静态方法": "STATICMETHOD",
    "抽象方法": "ABSTRACTMETHOD",
    # ── Bra-Ket 人格协作关键字 ──
    "人格基态": "PERSONA_BASIS",
    "系统": "SYSTEM",
    # ── OOP 关键字（v3.0 预备·🟡 保留） ──
    "对象": "OBJECT",
    "实例": "INSTANCE",
    "继承": "EXTENDS",
    "接口": "INTERFACE",
    "抽象": "ABSTRACT",
    "虚函数": "VIRTUAL",
    "泛型": "GENERIC",
    "重载": "OVERLOAD",
    "重写": "OVERRIDE",
    "构造函数": "CONSTRUCTOR",
    "析构函数": "DESTRUCTOR",
    "自身": "SELF",
    # ── 访问控制（v3.0 预备） ──
    "公开": "PUBLIC",
    "私有": "PRIVATE",
    "保护": "PROTECTED",
    "内部": "INTERNAL",
    # ── 生成器/迭代器 ──
    "迭代器": "ITERATOR",
    "生成器": "GENERATOR",
    "流": "STREAM",
    # ── 异步/并发（v3.0 预备） ──
    "协程": "COROUTINE",
    "线程": "THREAD",
    "锁": "MUTEX",
    "原子": "ATOMIC",
    "通道": "CHANNEL",
    "信号量": "SEMAPHORE",
    "并行": "PARALLEL",
    "串行": "SERIAL",
    # ═══════════════════════════════════════
    # 龍魂专属关键字（不可被普通编译器识别）
    # ═══════════════════════════════════════
    # ── 三色审计 ──
    "三色审计": "TRI_COLOR_AUDIT",
    "审计中": "AUDITING",
    "已审计": "AUDITED",
    # ── DNA 追溯 ──
    "DNA追溯": "DNA_TRACE",
    "DNA登记": "DNA_REGISTER",
    "DNA验证": "DNA_VERIFY",
    "DNA签章": "DNA_SIGN",
    # ── 量子 ──
    "量子纠缠": "QUANTUM_ENTANGLE",
    "量子态": "QUANTUM_STATE",
    "量子叠加": "SUPERPOSITION",
    "量子坍缩": "COLLAPSE",
    # ── 回滚 ──
    "生成回滚点": "CREATE_ROLLBACK",
    "回滚": "ROLLBACK",
    "验证回滚": "VERIFY_ROLLBACK",
    # ── 钩子 ──
    "钩子": "HOOK",
    "前置钩子": "BEFORE_HOOK",
    "后置钩子": "AFTER_HOOK",
    # ── 熔断 ──
    "熔断": "ABORT",
    "冷启动": "COLD_START",
    "热启动": "HOT_START",
    "终止执行": "EXIT_PROGRAM",
    # ── 路由/意图（v2.0 §11） ──
    "路由": "ROUTE",
    "意图": "INTENT",
    "上下文": "CONTEXT",
    "路由到": "ROUTE_TO",
    "命中": "HIT",
    "分发": "DISPATCH",
    "订阅": "SUBSCRIBE",
    "发布": "PUBLISH",
    # ── 加密/主权 ──
    "加密": "ENCRYPT_KW",
    "解密": "DECRYPT_KW",
    "签章": "SIGN_MSG",
    "验签": "VERIFY_SIGN",
    # ── 龍魂文化关键字（v2.0 §2.3） ──
    "数字根": "DIGITAL_ROOT",
    "数字根熔断": "DR_FUSE",
    "五行": "WUXING",
    "八卦": "BAGUA",
    "天干": "TIANGAN",
    "地支": "DIZHI",
    "三才": "SANCAI",
    "太极": "TAIJI",
    "蒙卦": "MENGGUA",
    "启智": "ENLIGHTEN",
    "龍盾": "LONGDUN",
    "通心译": "ETE",
    # ── 审计状态符号 ──
    "预警": "WARNING_PRE",
    "警报": "ALERT",
    "黑名单": "BLACKLIST",
    "红线词": "RED_LINE_WORD",
    "红线词集": "RED_LINE_SET",
    # ── v1.0 历史别名（向后兼容·🟢） ──
    "打印": "PRINT",
    "小数": "FLOAT_TYPE",
    "文本": "STRING_TYPE",
    "真假": "BOOLEAN_TYPE",
    "主函数": "ENTRY",
    "主程序": "ENTRY",
    # ── 内置函数别名 ──
    "当前时间": "NOW_FN",
    "长度": "LEN_FN",
    "转字符串": "TO_STR_FN",
    "转整数": "TO_INT_FN",
}


# 运算符字符映射（双字符优先）
OPERATORS = {
    # 复合赋值（双字符·必须优先于单字符）
    "+=": "PLUS_ASSIGN",
    "-=": "MINUS_ASSIGN",
    "*=": "STAR_ASSIGN",
    "/=": "SLASH_ASSIGN",
    "%=": "PERCENT_ASSIGN",
    # 比较
    "==": "EQ",
    "!=": "NE",
    "<=": "LE",
    ">=": "GE",
    # 逻辑
    "&&": "AND",
    "||": "OR",
    # 其他双字符
    "->": "ARROW",
    "**": "POWER",
    "//": "FLOOR_DIV",
    # 单字符
    "+": "PLUS",
    "-": "MINUS",
    "*": "STAR",
    "/": "SLASH",
    "%": "PERCENT",
    "=": "ASSIGN",
    "<": "LT",
    ">": "GT",
    "!": "NOT",
}


# 单字符标点
PUNCTUATION = {
    "(": "LPAREN",
    ")": "RPAREN",
    "{": "LBRACE",
    "}": "RBRACE",
    "[": "LBRACKET",
    "]": "RBRACKET",
    ",": "COMMA",
    ";": "SEMICOLON",
    ":": "COLON",
    ".": "DOT",
    "@": "AT",
}
