# 龍魂系统 · 工程实现层
# License: MulanPSL v2 (https://license.coscl.org.cn/MulanPSL2)
# 文化归属: 思想框架归龍魂核心思想层 (CC BY-NC-SA 4.0)
# DNA: #龍芯⚡️丙午·癸未·甲申·庚午·䷙大畜-DIGITAL-FLOW-FIELD-APP-v2.0-UID9622
# 署名: UID9622（诸葛鑫·Lucky）

"""数字流场可视化器 · Streamlit 主界面。"""

from __future__ import annotations

import base64
import csv
import hashlib
import io
import json
import os
import re
from datetime import datetime
from typing import Optional

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd
import plotly.express as px
import requests
import streamlit as st

from flow_engine.core import TextAnalysis, analyze_text, char_digital_root, generate_text_fingerprint
from flow_engine.particle_engine import ParticleSystem
from flow_engine.color_schemes import SCHEME_NAMES


PROJECT_DNA = "#龍芯⚡️丙午·癸未·甲申·庚午·䷙大畜-DIGITAL-FLOW-FIELD-v2.0-UID9622"
CONFIRM_CODE = "#CONFIRM🌌9622-ONLY-ONCE🧬LK9X-772Z"


def input_dna(text: str) -> str:
    """基于输入内容生成 DNA 追溯码。"""
    h = hashlib.sha256(text.encode("utf-8")).hexdigest()[:8]
    return f"{PROJECT_DNA}-{h}"


def fetch_url_text(url: str, timeout: int = 10) -> str:
    """抓取 URL 并提取正文文本。"""
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/120.0.0.0 Safari/537.36"
        )
    }
    resp = requests.get(url, headers=headers, timeout=timeout)
    resp.raise_for_status()
    html = resp.text
    # 简单去标签
    text = re.sub(r"<script[^>]*>.*?</script>", "", html, flags=re.S | re.I)
    text = re.sub(r"<style[^>]*>.*?</style>", "", text, flags=re.S | re.I)
    text = re.sub(r"<[^>]+>", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def fig_to_png_bytes(fig) -> bytes:
    """将 matplotlib Figure 转为 PNG 字节。"""
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=120, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close(fig)
    buf.seek(0)
    return buf.read()


def save_export(path: str, data: bytes | str) -> str:
    """保存导出文件到 output/ 目录。"""
    os.makedirs(os.path.dirname(path) or "output", exist_ok=True)
    mode = "w" if isinstance(data, str) else "wb"
    with open(path, mode, encoding="utf-8" if mode == "w" else None) as f:
        f.write(data)
    return path


def build_html_report(analysis: TextAnalysis, png_b64: str, dna: str) -> str:
    """生成 HTML 审计报告。"""
    rows = "\n".join(
        f"<tr><td>{i}</td><td>{analysis.counts[i]}</td><td>{analysis.percentages[i]:.2f}%</td></tr>"
        for i in range(1, 10)
    )
    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<title>龍魂 · 数字流场报告</title>
<style>
body {{ background:#0a0a1a; color:#eee; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; padding:24px; }}
h1 {{ color:#f58231; }} table {{ border-collapse:collapse; margin:16px 0; }} td,th {{ border:1px solid #444; padding:6px 12px; }}
th {{ background:#222; }} .dna {{ color:#888; font-size:12px; margin:12px 0; }}
</style>
</head>
<body>
<h1>🐲 数字流场报告</h1>
<p class="dna">{dna}</p>
<p>总粒子: {analysis.total} · χ²: {analysis.chi2:.4f} · 随机性: {"✅ 符合" if analysis.is_random_like else "⚠️ 偏离"}</p>
<p>最活跃: {analysis.most_active_root} ({analysis.most_active_pct:.2f}%) · 最冷门: {analysis.least_active_root} ({analysis.least_active_pct:.2f}%)</p>
<img src="data:image/png;base64,{png_b64}" style="max-width:100%; border:1px solid #333;">
<table><tr><th>数字根</th><th>次数</th><th>占比</th></tr>{rows}<tr><th>合计</th><th>{analysis.total}</th><th>100%</th></tr></table>
<p style="margin-top:24px; color:#666; font-size:12px;">Generated by 龍魂数字流场 v2.0 · MulanPSL v2</p>
</body>
</html>"""


def main() -> None:
    st.set_page_config(page_title="龍魂 · 数字流场可视化器", layout="wide")

    # 侧边栏：主权锚定 + 参数
    with st.sidebar:
        st.markdown("### 🐲 数字流场 v2.0")
        st.markdown(
            f"<p style='font-size:12px; color:#888;'>DNA: {PROJECT_DNA}</p>",
            unsafe_allow_html=True,
        )
        st.markdown(f"确认码: `{CONFIRM_CODE}`")

        st.markdown("---")
        st.markdown("#### 🎛️ 流场参数")
        speed = st.slider("流动速度", 0.1, 3.0, 1.0, 0.1)
        trail_length = st.slider("轨迹长度", 0, 50, 20, 5)
        center_gravity = st.slider("中心引力", 0.0, 1.0, 0.3, 0.05)
        scheme = st.selectbox("颜色方案", list(SCHEME_NAMES.keys()), format_func=lambda k: SCHEME_NAMES[k])
        max_particles = st.slider("最大粒子数", 100, 5000, 3000, 100)
        particle_scale = st.slider("粒子缩放", 0.5, 3.0, 1.0, 0.1)

        st.markdown("---")
        st.markdown("#### 👁️ 显示控制")
        show_trail = st.checkbox("显示轨迹", True)
        show_labels = st.checkbox("显示字符标签", False)
        show_hud = st.checkbox("显示 HUD 统计", True)

        st.markdown("---")
        st.markdown("#### 🟢 三色审计")
        st.markdown("🟢 算法正确 · 🟡 性能保护 · 🟢 主权锚定")

    # 主内容区
    st.title("🐲 龍魂 · 数字流场可视化器 v2.0")
    st.caption("把文字变成流动的结构 · 去黑箱的第一站")

    tab_input, tab_file, tab_url = st.tabs(["📝 直接输入", "📄 文件上传", "🌐 URL 抓取"])

    text_input = ""
    source_label = "手动输入"

    with tab_input:
        text_input = st.text_area(
            "输入文本",
            height=180,
            placeholder="在此粘贴任意文本，中文、英文、代码均可……",
        )

    with tab_file:
        uploaded = st.file_uploader("上传 .txt / .md / .csv / .json", type=["txt", "md", "csv", "json"])
        if uploaded is not None:
            raw = uploaded.read()
            try:
                import chardet
                enc = chardet.detect(raw).get("encoding") or "utf-8"
            except Exception:
                enc = "utf-8"
            try:
                text_input = raw.decode(enc, errors="ignore")
                source_label = f"文件: {uploaded.name}"
            except Exception as e:
                st.error(f"文件解码失败: {e}")

    with tab_url:
        url = st.text_input("输入 URL", placeholder="https://example.com/article")
        if st.button("抓取正文") and url:
            try:
                text_input = fetch_url_text(url)
                source_label = f"URL: {url}"
                st.success("抓取成功")
            except Exception as e:
                st.error(f"抓取失败: {e}")

    if not text_input.strip():
        st.info("请输入文本、上传文件或抓取 URL 后点击生成。")
        return

    if st.button("🚀 生成流场", type="primary"):
        with st.spinner("正在计算数字根与粒子流场……"):
            analysis = analyze_text(text_input)
            if analysis.total == 0:
                st.warning("未能从输入中提取到有效字符（可能全是空白或控制字符）。")
                return

            dna = input_dna(text_input)
            ps = ParticleSystem(max_particles=max_particles, trail_length=trail_length)
            ps.load_text(text_input, scheme=scheme)
            # 预热若干步，让流场进入稳定动态
            ps.update(speed=speed, center_gravity=center_gravity, steps=60)

            fig = ps.render(
                show_trail=show_trail,
                show_labels=show_labels,
                show_hud=show_hud,
                particle_scale=particle_scale,
                figsize=(8, 8),
            )
            png_bytes = fig_to_png_bytes(fig)
            png_b64 = base64.b64encode(png_bytes).decode("ascii")

        # 结果展示
        st.markdown(f"**DNA**: `{dna}`")

        col1, col2 = st.columns([1, 2])
        with col1:
            st.markdown("### 📊 实时统计")
            st.metric("总粒子", analysis.total)
            st.metric("χ² 统计量", f"{analysis.chi2:.4f}")
            st.metric("随机性判定", "✅ 符合" if analysis.is_random_like else "⚠️ 偏离")
            st.metric(
                "最活跃 / 最冷门",
                f"{analysis.most_active_root} ({analysis.most_active_pct:.2f}%) / "
                f"{analysis.least_active_root} ({analysis.least_active_pct:.2f}%)",
            )
            if analysis.sampled:
                st.warning(f"⚠️ 输入过长（{analysis.raw_length} 字符），已等距采样至 {analysis.total} 字符分析。")

            st.markdown("### 🧬 数字指纹")
            st.code(analysis.fingerprint or "（空）", language="text")

        with col2:
            st.image(png_bytes, use_container_width=True)

        # 图表
        st.markdown("---")
        chart_col1, chart_col2 = st.columns(2)
        df_dist = pd.DataFrame(
            {
                "数字根": list(range(1, 10)),
                "次数": analysis.counts[1:],
                "占比(%)": analysis.percentages[1:],
            }
        )
        with chart_col1:
            fig_bar = px.bar(df_dist, x="数字根", y="次数", color="次数", color_continuous_scale="turbo")
            st.plotly_chart(fig_bar, use_container_width=True)
        with chart_col2:
            fig_pie = px.pie(df_dist, names="数字根", values="次数", hole=0.3)
            st.plotly_chart(fig_pie, use_container_width=True)

        # 字符映射表
        with st.expander("📖 字符映射表（前 200 字符）"):
            mapping = []
            for idx, ch in enumerate(text_input[:500]):
                if not ch.strip():
                    continue
                mapping.append(
                    {"位置": idx, "字符": ch, "Unicode": ord(ch), "数字根": char_digital_root(ch)}
                )
            st.dataframe(pd.DataFrame(mapping[:200]), use_container_width=True)

        # 导出
        st.markdown("---")
        st.markdown("### 📤 导出")
        export_col1, export_col2, export_col3, export_col4 = st.columns(4)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        base_name = f"flow_field_{timestamp}"

        payload = {
            "dna": dna,
            "timestamp": datetime.now().isoformat(),
            "source": source_label,
            "analysis": {
                "total": analysis.total,
                "counts": analysis.counts,
                "percentages": analysis.percentages,
                "chi2": analysis.chi2,
                "is_random_like": analysis.is_random_like,
                "most_active_root": analysis.most_active_root,
                "least_active_root": analysis.least_active_root,
                "fingerprint": analysis.fingerprint,
                "sampled": analysis.sampled,
                "raw_length": analysis.raw_length,
            },
            "particles": ps.to_dict(limit=500),
        }

        with export_col1:
            json_str = json.dumps(payload, ensure_ascii=False, indent=2)
            json_path = save_export(f"output/{base_name}.json", json_str)
            with open(json_path, "rb") as f:
                st.download_button("⬇️ JSON", f, file_name=f"{base_name}.json", mime="application/json")

        with export_col2:
            buf = io.StringIO()
            writer = csv.writer(buf)
            from flow_engine.core import distribution_to_csv_rows
            writer.writerows(distribution_to_csv_rows(analysis))
            csv_path = save_export(f"output/{base_name}.csv", buf.getvalue())
            with open(csv_path, "rb") as f:
                st.download_button("⬇️ CSV", f, file_name=f"{base_name}.csv", mime="text/csv")

        with export_col3:
            html_path = save_export(f"output/{base_name}.html", build_html_report(analysis, png_b64, dna))
            with open(html_path, "rb") as f:
                st.download_button("⬇️ HTML", f, file_name=f"{base_name}.html", mime="text/html")

        with export_col4:
            png_path = save_export(f"output/{base_name}.png", png_bytes)
            st.download_button("⬇️ PNG", png_bytes, file_name=f"{base_name}.png", mime="image/png")

        # 页脚
        st.markdown("---")
        st.markdown(
            "<p style='text-align:center; color:#666; font-size:12px;'>"
            "龍魂数字流场 v2.0 · 纯本地计算 · MulanPSL v2 · UID9622"
            "</p>",
            unsafe_allow_html=True,
        )


if __name__ == "__main__":
    main()
