#!/usr/bin/env python3
# DNA: #龍芯⚡️丙午·丙申·癸酉·乙卯·临-SEMANTIC-GUARD-GENERATOR-v∞-F9CC6527
# CREATOR: UID9622
# PROTOCOL: 龍魂君子协议 · CC BY-NC-SA 4.0 · L0 世界老百姓最高
"""Generate a semantic guard rule that conforms to rule_template_schema v1.1."""
import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

BIN_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = BIN_DIR.parent
PROTO_DIR = PROJECT_ROOT / "01_protocols" / "semantic_guard"

DEFAULT_RULE_FILE = PROTO_DIR / "tongxin_guard_rules.json"


def load_json_with_header(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        lines = f.readlines()
    body = [line for line in lines if not line.strip().startswith(">") and line.strip()]
    return json.loads("".join(body))


def write_with_header(path: Path, data: dict):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"> DNA: {data['dna']}\n")
        f.write("> CREATOR: UID9622\n")
        f.write("> PROTOCOL: 龍魂君子协议 · CC BY-NC-SA 4.0 · L0 世界老百姓最高\n\n")
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")


def make_rule(args, categories):
    cat = categories.get(args.category, {})
    action = args.action or cat.get("default_action", "external_feed_append_only")
    severity = args.severity or cat.get("default_severity", "🟡")

    if not re.fullmatch(r"[A-Z][A-Z0-9_]*", args.id):
        raise ValueError(f"Rule id must match [A-Z][A-Z0-9_]*: {args.id}")
    if len(args.description) < 20:
        raise ValueError("Rule description must be at least 20 characters.")
    if not args.patterns:
        raise ValueError("At least one pattern is required.")
    for p in args.patterns:
        re.compile(p)

    now_utc = datetime.now(timezone.utc).isoformat()
    now_cn = datetime.now().astimezone().isoformat()

    return {
        "id": args.id,
        "category": args.category,
        "name": args.name,
        "description": args.description,
        "patterns": list(args.patterns),
        "negative_patterns": list(args.negative_patterns or []),
        "severity": severity,
        "action": action,
        "priority": args.priority,
        "enabled": True,
        "version": args.version,
        "created_at": now_utc,
        "updated_at": now_cn,
        "author": args.author,
        "metadata": {
            "source": args.source,
            "evidence_examples": list(args.evidence or [f"示例：匹配规则「{args.name}」的文本片段。"]),
            "counter_examples": [],
            "references": list(args.reference or []),
            "tags": [args.category],
            "notes": args.notes or "",
        },
        "audit": {
            "status": "draft",
            "reviewer": "",
            "reviewed_at": "",
            "comments": "Generated by lh_sg_generator.py; awaiting UID9622 review.",
        },
    }


def main():
    parser = argparse.ArgumentParser(description="Generate a semantic guard rule.")
    parser.add_argument("--id", required=True, help="Uppercase rule ID, e.g. MY_NEW_RULE")
    parser.add_argument("--category", required=True, help="Existing category key")
    parser.add_argument("--name", required=True, help="Short Chinese name")
    parser.add_argument("--description", required=True, help="At least 20 characters")
    parser.add_argument("--patterns", nargs="+", required=True, help="Regex patterns")
    parser.add_argument("--negative-patterns", nargs="*", help="Negative regex patterns")
    parser.add_argument("--severity", choices=["🟢", "🟡", "🔴"], help="Override severity")
    parser.add_argument("--action", help="Override action key")
    parser.add_argument("--priority", type=int, default=50, help="Priority 0-100")
    parser.add_argument("--version", default="2.2.0", help="Rule version")
    parser.add_argument("--author", default="UID9622", help="Author")
    parser.add_argument("--source", default="manual", help="Source tag")
    parser.add_argument("--evidence", nargs="*", help="Evidence example strings")
    parser.add_argument("--reference", nargs="*", help="Reference URLs")
    parser.add_argument("--notes", default="", help="Internal notes")
    parser.add_argument("--file", type=Path, default=None, help="Target rule file")
    parser.add_argument("--output", choices=["json", "append"], default="json", help="Output mode")
    args = parser.parse_args()

    rule_file = args.file or DEFAULT_RULE_FILE
    if rule_file.exists():
        data = load_json_with_header(rule_file)
    else:
        print(f"🔴 Rule file not found: {rule_file}")
        sys.exit(1)

    categories = data.get("categories", {})
    if args.category not in categories:
        print(f"ERROR: category '{args.category}' not found. Available: {list(categories.keys())}", file=sys.stderr)
        sys.exit(1)

    new_rule = make_rule(args, categories)

    if args.output == "append":
        data.setdefault("rules", []).append(new_rule)
        data["updated_at"] = datetime.now().astimezone().isoformat()
        write_with_header(rule_file, data)
        print(f"✅ Appended rule {new_rule['id']} to {rule_file}")
        print(f"   Run `python3 {BIN_DIR / 'lh_sg_auditor.py'}` to validate.")
    else:
        print(json.dumps(new_rule, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
