# DNA: #龍芯⚡️丙午·丙申·甲子·甲戌·䷍大有-CODE-补DNA-2efe3d5d
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
🐉 龍魂 · AI身份标识与互认协议引擎 v2.0
DNA: [[GENERATED_BY_LH_DNA_GENERATOR_V3]]-AI-IDENTITY-v2.0
确认码: #CONFIRM🌌9622-ONLY-ONCE🧬LK9X-772Z
# 归属名: 诸葛鑫 | UID9622 · 龍芯北辰
GPG: A2D0092CEE2E5BA87035600924C3704A8CC26D5F

AI内容强制标识 · 互认拦截 · 本地主权豁免 · 配置化规则 · 审计归档
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import os
import re
import sys
import time
import unittest
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Set

CONFIRM_CODE = "#CONFIRM🌌9622-ONLY-ONCE🧬LK9X-772Z"
GPG_FINGERPRINT = "A2D0092CEE2E5BA87035600924C3704A8CC26D5F"
OWNER_UID = "UID9622"


# ═══════════════════════════════════════════════════════════════════════════════
# 0. 数据模型
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class WatermarkRule:
    """水印规则。"""
    content_type: str       # text / code / image / audio / video / api
    prefix: str = ""        # 内容前缀
    suffix: str = ""        # 内容后缀
    header_name: str = ""   # HTTP 头名
    header_value: str = ""  # HTTP 头值
    comment: str = ""       # 代码注释
    enabled: bool = True


@dataclass
class AIIndicator:
    """AI 检测指标。"""
    pattern: str
    weight: float           # 置信度权重
    description: str
    location: str = "any"   # any / prefix / header / metadata


@dataclass
class RecognitionResult:
    """互认检测结果。"""
    timestamp: str
    source_is_ai: bool
    target_is_ai: bool
    action: str             # pass / stop / audit
    confidence: float       # 0-1
    reason: str
    dna: str
    tricolor: str = "🟢"

    def to_dict(self) -> Dict:
        return asdict(self)


@dataclass
class IdentityAuditLog:
    """身份审计日志。"""
    timestamp: str
    event_type: str         # inject / detect / intercept / exempt
    content_type: str
    result: str
    confidence: float
    reason: str
    dna: str



# ═══════════════════════════════════════════════════════════════════════════════
# 1. 配置管理
# ═══════════════════════════════════════════════════════════════════════════════

class IdentityConfig:
    """身份标识配置管理器。"""

    DEFAULT_WATERMARKS: List[WatermarkRule] = [
        WatermarkRule("text", prefix="[AI]", enabled=True),
        WatermarkRule("code", comment="// AI-Generated", enabled=True),
        WatermarkRule("api", header_name="X-AI-Identity", header_value="true", enabled=True),
        WatermarkRule("api", header_name="X-Longhun-DNA", header_value="", enabled=True),
        WatermarkRule("image", comment="AI", enabled=True),
        WatermarkRule("audio", prefix="我是AI助手。", enabled=True),
        WatermarkRule("video", comment="AI", enabled=True),
    ]

    DEFAULT_INDICATORS: List[AIIndicator] = [
        AIIndicator(r'^\[AI\]', 0.9, "AI文字前缀", "prefix"),
        AIIndicator(r'^🤖', 0.9, "AI机器人表情", "prefix"),
        AIIndicator(r'^🧠', 0.85, "AI大脑表情", "prefix"),
        AIIndicator(r'我是AI', 0.8, "AI自称", "any"),
        AIIndicator(r'AI助手', 0.8, "AI助手自称", "any"),
        AIIndicator(r'龙魂AI', 0.85, "龙魂AI标识", "any"),
        AIIndicator(r'X-AI-Identity:\s*true', 0.95, "AI身份头", "header"),
        AIIndicator(r'AI-Generated', 0.9, "AI生成注释", "any"),
        AIIndicator(r'generated by ai', 0.85, "AI生成声明", "any"),
    ]

    def __init__(self, config_dir: Optional[Path] = None) -> None:
        self.config_dir = config_dir or (Path.home() / ".longhun" / "agent" / "identity")
        self.config_dir.mkdir(parents=True, exist_ok=True)
        os.chmod(self.config_dir, 0o700)
        self.watermarks_file = self.config_dir / "watermarks.json"
        self.indicators_file = self.config_dir / "indicators.json"
        self.exempt_file = self.config_dir / "exempt_list.json"
        self._watermarks = self._load_watermarks()
        self._indicators = self._load_indicators()
        self._exempt: Set[str] = self._load_exempt()

    def _load_watermarks(self) -> List[WatermarkRule]:
        if self.watermarks_file.exists():
            try:
                with open(self.watermarks_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                return [WatermarkRule(**w) for w in data.get("watermarks", [])]
            except Exception as exc:
                logging.warning("水印配置加载失败: %s", exc)
        return self.DEFAULT_WATERMARKS[:]

    def _load_indicators(self) -> List[AIIndicator]:
        if self.indicators_file.exists():
            try:
                with open(self.indicators_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                return [AIIndicator(**i) for i in data.get("indicators", [])]
            except Exception as exc:
                logging.warning("指标配置加载失败: %s", exc)
        return self.DEFAULT_INDICATORS[:]

    def _load_exempt(self) -> Set[str]:
        if self.exempt_file.exists():
            try:
                with open(self.exempt_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                return set(data.get("exempt_uids", []))
            except Exception as exc:
                logging.warning("豁免列表加载失败: %s", exc)
        return {OWNER_UID}  # 默认豁免 UID9622

    def save(self) -> None:
        for path, data in (
            (self.watermarks_file, {"watermarks": [asdict(w) for w in self._watermarks]}),
            (self.indicators_file, {"indicators": [asdict(i) for i in self._indicators]}),
            (self.exempt_file, {"exempt_uids": list(self._exempt)}),
        ):
            path.parent.mkdir(parents=True, exist_ok=True)
            tmp = path.with_suffix(".tmp")
            with open(tmp, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
                f.flush()
                os.fsync(f.fileno())
            os.replace(tmp, path)
            os.chmod(path, 0o600)

    def get_watermark(self, content_type: str) -> Optional[WatermarkRule]:
        for w in self._watermarks:
            if w.content_type == content_type and w.enabled:
                return w
        return None

    def is_exempt(self, uid: str) -> bool:
        return uid in self._exempt

    def add_exempt(self, uid: str) -> None:
        self._exempt.add(uid)
        self.save()

    def remove_exempt(self, uid: str) -> None:
        self._exempt.discard(uid)
        self.save()


# ═══════════════════════════════════════════════════════════════════════════════
# 2. 水印引擎
# ═══════════════════════════════════════════════════════════════════════════════

class WatermarkEngine:
    """AI 标识水印注入与检测引擎。"""

    def __init__(self, config: Optional[IdentityConfig] = None) -> None:
        self.config = config or IdentityConfig()

    def inject(self, content: str, content_type: str = "text",
               skip_if_present: bool = True) -> str:
        """注入 AI 标识水印。"""
        rule = self.config.get_watermark(content_type)
        if not rule:
            return content

        # 检查是否已有标识（避免重复）
        if skip_if_present and self._has_watermark(content, content_type):
            return content

        if content_type == "text":
            return f"{rule.prefix} {content}"
        elif content_type == "code":
            return f"{rule.comment}\n{content}"
        elif content_type == "api":
            # API 返回的是 HTTP 头字典，这里简化处理
            return content  # 实际由网关层注入头
        elif content_type in ("image", "video"):
            return content  # 图像/视频水印需外部工具处理
        elif content_type == "audio":
            return f"{rule.prefix} {content}"
        return content

    def _has_watermark(self, content: str, content_type: str) -> bool:
        """检查是否已有水印。"""
        rule = self.config.get_watermark(content_type)
        if not rule:
            return False
        if rule.prefix and content.startswith(rule.prefix):
            return True
        if rule.comment and rule.comment in content:
            return True
        return False

    def detect(self, content: str, headers: Optional[Dict[str, str]] = None) -> Tuple[bool, float, str]:
        """检测内容是否为 AI 生成。返回 (是否AI, 置信度, 原因)。"""
        confidence = 0.0
        reasons: List[str] = []

        # 文本/内容检测
        for indicator in self.config._indicators:
            try:
                if re.search(indicator.pattern, content, re.IGNORECASE):
                    confidence += indicator.weight
                    reasons.append(indicator.description)
            except re.error:
                continue

        # HTTP 头检测
        if headers:
            for indicator in self.config._indicators:
                if indicator.location == "header":
                    for k, v in headers.items():
                        header_str = f"{k}: {v}"
                        try:
                            if re.search(indicator.pattern, header_str, re.IGNORECASE):
                                confidence += indicator.weight
                                reasons.append(f"Header {indicator.description}")
                        except re.error:
                            continue

        # 归一化置信度到 0-1
        confidence = min(1.0, confidence)
        is_ai = confidence >= 0.5
        reason = "; ".join(reasons) if reasons else "无AI标识"
        return is_ai, round(confidence, 4), reason

    def strip(self, content: str, content_type: str = "text") -> str:
        """移除水印（仅本地测试使用）。"""
        rule = self.config.get_watermark(content_type)
        if not rule:
            return content
        if rule.prefix and content.startswith(rule.prefix):
            content = content[len(rule.prefix):].strip()
        if rule.comment:
            content = content.replace(rule.comment + "\n", "")
            content = content.replace(rule.comment, "")
        return content


# ═══════════════════════════════════════════════════════════════════════════════
# 3. 互认拦截引擎
# ═══════════════════════════════════════════════════════════════════════════════

class RecognitionEngine:
    """AI 互认拦截引擎。"""

    def __init__(self, config: Optional[IdentityConfig] = None,
                 watermark: Optional[WatermarkEngine] = None,
                 audit_dir: Optional[Path] = None) -> None:
        self.config = config or IdentityConfig()
        self.watermark = watermark or WatermarkEngine(self.config)
        self.audit_dir = audit_dir or (Path.home() / ".longhun" / "agent" / "identity" / "audit")
        self.audit_dir.mkdir(parents=True, exist_ok=True)
        os.chmod(self.audit_dir, 0o700)
        self._audit_file = self.audit_dir / "identity_audit.jsonl"
        self._intercept_file = self.audit_dir / "ai_intercepts.jsonl"

    def _generate_dna(self, prefix: str = "IDENTITY") -> str:
        h = hashlib.sha256(f"{prefix}{time.time()}{os.urandom(8)}".encode()).hexdigest()[:8].upper()
        return f"[[GENERATED_BY_LH_DNA_GENERATOR_V3]]-{prefix}-{h}-v2.0"

    def is_local_exempt(self, uid: Optional[str] = None) -> bool:
        """检查本地主权豁免。"""
        # 环境变量优先
        if os.environ.get("LONGHUN_LOCAL_SOVEREIGNTY", "").lower() in ("true", "1", "yes"):
            return True
        # UID 检查
        if uid and self.config.is_exempt(uid):
            return True
        return False

    def recognize(self, source_content: str, target_content: str,
                  source_headers: Optional[Dict] = None,
                  target_headers: Optional[Dict] = None,
                  source_uid: Optional[str] = None) -> RecognitionResult:
        """
        AI 互认检测。
        如果双方都是 AI → 拦截。
        如果本地豁免 → 放行。
        """
        timestamp = datetime.now().isoformat()

        # 本地豁免检查
        if self.is_local_exempt(source_uid):
            result = RecognitionResult(
                timestamp=timestamp,
                source_is_ai=True,  # 本地可以是AI
                target_is_ai=True,
                action="pass",
                confidence=1.0,
                reason="本地主权豁免 (UID9622)",
                dna=self._generate_dna("EXEMPT"),
                tricolor="🟢"
            )
            self._log_audit("exempt", "recognition", "pass", 1.0, "本地豁免")
            return result

        # 检测双方身份
        source_is_ai, source_conf, source_reason = self.watermark.detect(source_content, source_headers)
        target_is_ai, target_conf, target_reason = self.watermark.detect(target_content, target_headers)

        # 判断
        if source_is_ai and target_is_ai:
            action = "stop"
            reason = f"AI-AI互认拦截: 源{source_conf} 目标{target_conf}"
            tricolor = "🔴"
            self._log_intercept(source_content, target_content, source_conf, target_conf)
        elif source_is_ai or target_is_ai:
            action = "pass"
            reason = f"人机对话: 源AI={source_is_ai}({source_conf}) 目标AI={target_is_ai}({target_conf})"
            tricolor = "🟢"
        else:
            action = "pass"
            reason = "双方均非AI（或置信度不足）"
            tricolor = "🟢"

        confidence = (source_conf + target_conf) / 2 if source_conf or target_conf else 0.0

        result = RecognitionResult(
            timestamp=timestamp,
            source_is_ai=source_is_ai,
            target_is_ai=target_is_ai,
            action=action,
            confidence=round(confidence, 4),
            reason=reason,
            dna=self._generate_dna("RECOG"),
            tricolor=tricolor
        )
        self._log_audit("recognize", "recognition", action, confidence, reason)
        return result

    def _log_audit(self, event_type: str, content_type: str,
                   result: str, confidence: float, reason: str) -> None:
        entry = IdentityAuditLog(
            timestamp=datetime.now().isoformat(),
            event_type=event_type,
            content_type=content_type,
            result=result,
            confidence=confidence,
            reason=reason,
            dna=self._generate_dna("AUDIT")
        )
        with open(self._audit_file, "a", encoding="utf-8") as f:
            f.write(json.dumps(asdict(entry), ensure_ascii=False) + "\n")
            f.flush()

    def _log_intercept(self, source: str, target: str,
                         source_conf: float, target_conf: float) -> None:
        entry = {
            "timestamp": datetime.now().isoformat(),
            "event": "ai_ai_intercept",
            "source_preview": source[:100],
            "target_preview": target[:100],
            "source_confidence": source_conf,
            "target_confidence": target_conf,
            "dna": self._generate_dna("INTERCEPT")
        }
        with open(self._intercept_file, "a", encoding="utf-8") as f:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")
            f.flush()

    def get_stats(self) -> Dict:
        total = 0
        exempt = 0
        stopped = 0
        passed = 0
        if self._audit_file.exists():
            with open(self._audit_file, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        data = json.loads(line)
                        total += 1
                        et = data.get("event_type", "")
                        if et == "exempt":
                            exempt += 1
                        elif data.get("result") == "stop":
                            stopped += 1
                        else:
                            passed += 1
                    except json.JSONDecodeError:
                        continue
        return {
            "total_events": total,
            "exempt": exempt,
            "stopped": stopped,
            "passed": passed,
            "intercept_count": stopped,
            "watermark_rules": len([w for w in self.config._watermarks if w.enabled]),
            "indicators": len(self.config._indicators),
            "exempt_uids": list(self.config._exempt),
        }


# ═══════════════════════════════════════════════════════════════════════════════
# 4. 网关集成接口（函数级，无 Flask）
# ═══════════════════════════════════════════════════════════════════════════════

class GatewayIntegration:
    """
    网关集成接口。
    提供纯函数供 nginx/OpenResty/Lua/其他网关调用，不启动独立服务。
    """

    def __init__(self, recognition: Optional[RecognitionEngine] = None) -> None:
        self.recognition = recognition or RecognitionEngine()

    def check_request(self, headers: Dict[str, str], body: str,
                      source_uid: Optional[str] = None) -> Dict:
        """
        检查入站请求。
        返回标准结构供网关判断。
        """
        # 检测请求方是否为 AI
        is_ai, conf, reason = self.recognition.watermark.detect(body, headers)

        if is_ai and not self.recognition.is_local_exempt(source_uid):
            return {
                "action": "stop",
                "status_code": 403,
                "reason": f"AI-AI对话已暂停: {reason} (置信度{conf})",
                "tricolor": "🔴",
                "dna": self.recognition._generate_dna("GATEWAY"),
                "headers_to_add": {
                    "X-AI-Identity": "true",
                    "X-Longhun-Intercept": "true",
                }
            }

        return {
            "action": "pass",
            "status_code": 200,
            "reason": "人类用户或本地豁免",
            "tricolor": "🟢",
            "headers_to_add": {
                "X-AI-Identity": "true",
            }
        }

    def wrap_response(self, content: str, content_type: str = "text",
                      headers: Optional[Dict] = None) -> Tuple[str, Dict]:
        """
        包装出站响应。
        返回 (内容, 追加头)。
        """
        headers = headers or {}
        # 注入水印
        wrapped = self.recognition.watermark.inject(content, content_type)
        # 添加 AI 标识头
        headers["X-AI-Identity"] = "true"
        headers["X-Longhun-Version"] = "v2.0"
        return wrapped, headers


# ═══════════════════════════════════════════════════════════════════════════════
# 5. CLI
# ═══════════════════════════════════════════════════════════════════════════════

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="lh_ai_identity", description="🐉 龍魂AI身份标识与互认协议引擎 v2.0")
    p.add_argument("--version", action="store_true", help="显示版本")
    p.add_argument("--stats", action="store_true", help="显示统计")
    p.add_argument("--inject", metavar="TEXT", help="注入水印")
    p.add_argument("--type", default="text", choices=["text", "code", "audio", "image", "video", "api"], help="内容类型")
    p.add_argument("--detect", metavar="TEXT", help="检测是否为AI内容")
    p.add_argument("--recognize", nargs=2, metavar=("SRC", "TGT"), help="互认检测（源内容 目标内容）")
    p.add_argument("--exempt", action="store_true", help="显示豁免列表")
    p.add_argument("--add-exempt", metavar="UID", help="添加豁免UID")
    p.add_argument("--remove-exempt", metavar="UID", help="移除豁免UID")
    p.add_argument("--test", action="store_true", help="运行单元测试")
    return p


def main(argv: Optional[List[str]] = None) -> int:
    args = build_parser().parse_args(argv)

    if args.version:
        print(f"🐉 龍魂AI身份标识与互认协议引擎 v2.0")
        print(f"DNA: [[GENERATED_BY_LH_DNA_GENERATOR_V3]]-AI-IDENTITY-v2.0")
        print(f"确认码: {CONFIRM_CODE}")
        print(f"GPG: {GPG_FINGERPRINT}")
        return 0

    if args.test:
        sys.argv = [sys.argv[0]] if sys.argv else [""]
        unittest.main(module=__name__, exit=False, verbosity=2)
        return 0

    config = IdentityConfig()
    watermark = WatermarkEngine(config)
    recognition = RecognitionEngine(config, watermark)

    if args.stats:
        print(json.dumps(recognition.get_stats(), indent=2, ensure_ascii=False))
        return 0

    if args.exempt:
        print(f"豁免UID列表 ({len(config._exempt)} 个):")
        for uid in sorted(config._exempt):
            print(f"  🟢 {uid}")
        return 0

    if args.add_exempt:
        config.add_exempt(args.add_exempt)
        print(f"🟢 已添加豁免: {args.add_exempt}")
        return 0

    if args.remove_exempt:
        config.remove_exempt(args.remove_exempt)
        print(f"🟢 已移除豁免: {args.remove_exempt}")
        return 0

    if args.inject:
        result = watermark.inject(args.inject, args.type)
        print(f"🟢 注入结果:")
        print(result)
        return 0

    if args.detect:
        is_ai, conf, reason = watermark.detect(args.detect)
        print(f"{'🔴' if is_ai else '🟢'} 检测结果:")
        print(f"  是否AI: {is_ai}")
        print(f"  置信度: {conf}")
        print(f"  原因: {reason}")
        return 0

    if args.recognize:
        result = recognition.recognize(args.recognize[0], args.recognize[1])
        print(json.dumps(asdict(result), indent=2, ensure_ascii=False))
        return 0 if result.action != "stop" else 1

    build_parser().print_help()
    return 1


# ═══════════════════════════════════════════════════════════════════════════════
# 6. 单元测试（锚点断言）
# ═══════════════════════════════════════════════════════════════════════════════

class TestAIIdentity(unittest.TestCase):

    def setUp(self) -> None:
        import tempfile
        self.tmp = Path(tempfile.mkdtemp())
        self.config = IdentityConfig(config_dir=self.tmp)
        self.watermark = WatermarkEngine(self.config)
        self.recognition = RecognitionEngine(self.config, self.watermark, audit_dir=self.tmp)

    def tearDown(self) -> None:
        import shutil
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_01_confirm_code(self) -> None:
        """锚点：确认码必须匹配。"""
        self.assertEqual(CONFIRM_CODE, "#CONFIRM🌌9622-ONLY-ONCE🧬LK9X-772Z")

    def test_02_dna_format(self) -> None:
        """锚点：DNA 必须不含手写干支。"""
        dna = self.recognition._generate_dna()
        self.assertIn("GENERATED_BY_LH_DNA_GENERATOR_V3", dna)
        self.assertNotRegex(dna, r'丙午|丙申|癸亥|午时|巳时|未时|亥时')

    def test_03_watermark_inject(self) -> None:
        """锚点：水印注入必须包含 [AI] 前缀。"""
        result = self.watermark.inject("测试内容", "text")
        self.assertTrue(result.startswith("[AI]"))

    def test_04_watermark_detect(self) -> None:
        """锚点：带水印内容必须被检测为AI。"""
        marked = self.watermark.inject("测试", "text")
        is_ai, conf, reason = self.watermark.detect(marked)
        self.assertTrue(is_ai)
        self.assertGreaterEqual(conf, 0.5)

    def test_05_watermark_skip_duplicate(self) -> None:
        """锚点：已有水印内容不应重复注入。"""
        marked = self.watermark.inject("测试", "text")
        marked2 = self.watermark.inject(marked, "text")
        self.assertEqual(marked, marked2)

    def test_06_ai_ai_intercept(self) -> None:
        """锚点：AI-AI 对话必须被拦截。"""
        src = self.watermark.inject("源AI", "text")
        tgt = self.watermark.inject("目标AI", "text")
        result = self.recognition.recognize(src, tgt)
        self.assertEqual(result.action, "stop")
        self.assertEqual(result.tricolor, "🔴")

    def test_07_local_exempt(self) -> None:
        """锚点：本地豁免必须放行。"""
        os.environ["LONGHUN_LOCAL_SOVEREIGNTY"] = "true"
        try:
            src = self.watermark.inject("源", "text")
            tgt = self.watermark.inject("目标", "text")
            result = self.recognition.recognize(src, tgt, source_uid=OWNER_UID)
            self.assertEqual(result.action, "pass")
            self.assertEqual(result.tricolor, "🟢")
        finally:
            del os.environ["LONGHUN_LOCAL_SOVEREIGNTY"]

    def test_08_human_ai_pass(self) -> None:
        """锚点：人类-AI 对话必须通过。"""
        src = "我是人类"  # 无AI标识
        tgt = self.watermark.inject("AI回复", "text")
        result = self.recognition.recognize(src, tgt)
        self.assertEqual(result.action, "pass")
        self.assertEqual(result.tricolor, "🟢")

    def test_09_config_persistence(self) -> None:
        """锚点：配置必须可持久化。"""
        self.config.add_exempt("TEST_UID")
        self.config.save()
        config2 = IdentityConfig(config_dir=self.tmp)
        self.assertIn("TEST_UID", config2._exempt)

    def test_10_audit_log(self) -> None:
        """锚点：审计日志必须写入文件。"""
        self.recognition.recognize("人类", "AI")
        self.assertTrue(self.recognition._audit_file.exists())
        content = self.recognition._audit_file.read_text(encoding="utf-8")
        self.assertIn("recognize", content)

    def test_11_strip_watermark(self) -> None:
        """锚点：strip 必须能移除水印。"""
        marked = self.watermark.inject("测试", "text")
        stripped = self.watermark.strip(marked, "text")
        self.assertNotIn("[AI]", stripped)
        self.assertEqual(stripped.strip(), "测试")

    def test_12_gateway_check(self) -> None:
        """锚点：网关接口必须返回标准结构。"""
        gw = GatewayIntegration(self.recognition)
        result = gw.check_request({}, "人类内容")
        self.assertIn("action", result)
        self.assertIn("status_code", result)
        self.assertIn("headers_to_add", result)
        self.assertEqual(result["action"], "pass")


if __name__ == "__main__":
    sys.exit(main())
